server:
  port: 8081
spring:
  application:
    name: "bank"
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/bank"
    username: root
    password: mysqlrootpassword
  jpa:
    database: MYSQL
  hibernate:
    ddl-auto: update
      show-sql: true